import { Icon } from './Icon';
import { desktop, type PrivacyPreferences } from './storage';
export function Privacy({ values, onChange, root, onWorkspace }: { values: PrivacyPreferences; onChange: (key: string, value: boolean | string) => void; root: string; onWorkspace: () => void }) {
  function toggle(key: string, title: string, description: string, planned = true, defaultValue = true) {
    const checked = typeof values[key] === 'boolean' ? values[key] as boolean : defaultValue;
    return <div className="preference-row" key={key}><div><div className="preference-title">{title}{planned && <span className="planned">Planned</span>}</div><p>{description}</p></div><button type="button" className={`toggle ${checked ? 'on' : ''}`} role="switch" aria-checked={checked} aria-label={title} disabled={key === 'cloud' || key === 'manual' || key === 'join'} onClick={() => onChange(key, !checked)}><span /></button></div>;
  }
  return <article className="privacy-page">
    <div className="eyebrow">SETTINGS / PRIVACY</div><h1>Your meetings.<br />Your boundaries.</h1><p className="page-description">A quieter workflow starts with knowing what happens to your data.</p>
    <div className="privacy-note"><Icon name="shield" size={22} /><div><strong>You decide when capture begins.</strong><p>This shell does not record audio, join calls, or send meeting content to a processing service. Planned controls save preferences only.</p></div></div>
    <section><h2>Capture</h2>{toggle('manual', 'Start capture manually', 'Every prototype capture starts with your action.', false)}{toggle('join', 'Never auto-join meetings', 'QuietNote has no meeting bot or auto-join integration.', false)}{toggle('confirm', 'Confirm before recording', 'Ask for confirmation before starting the prototype.', false)}</section>
    <section><h2>Storage</h2>{toggle('audio', 'Keep audio locally', 'Preference for future audio capture. No audio files are created.')}{toggle('deleteAudio', 'Delete audio after processing', 'Future cleanup behavior; no deletion runs in this prototype.', true, false)}{toggle('transcripts', 'Keep transcripts locally', 'Desktop transcript files already stay in the local archive.')}</section>
    <section><h2>Processing</h2>{toggle('local', 'Prefer local processing', 'On-device transcription is not implemented yet.')}{toggle('cloud', 'Allow cloud fallback', 'Unavailable. No cloud processing provider is connected.', true, false)}</section>
    <section><h2>Retention <span className="planned">Planned</span></h2><div className="preference-row"><div><div className="preference-title">Keep meeting data</div><p>Preference only. This prototype never automatically deletes files.</p></div><select aria-label="Keep meeting data" value={String(values.retention ?? 'forever')} onChange={e => onChange('retention', e.target.value)}><option value="forever">Keep forever</option><option value="30">Delete after 30 days</option><option value="7">Delete after 7 days</option></select></div></section>
    <section><h2>Local archive</h2><p className="archive-path">{root}</p><p className="subtle">Each meeting has editable Markdown, a separate transcript, and JSON metadata.</p><button className="secondary" disabled={!desktop} onClick={onWorkspace}>Open Markdown workspace<Icon name="arrow" /></button>{!desktop && <p className="subtle">The full filesystem workspace is available in the desktop app.</p>}</section>
    <section className="about-section"><h2>QuietNote <span className="planned">Prototype 0.1.0</span></h2><p>Built on <a href="https://github.com/erictli/scratch" target="_blank" rel="noreferrer">Scratch by Eric Li</a>, licensed under MIT. Original editor and local-file foundation preserved.</p><details><summary>MIT license & attribution</summary><p>Copyright (c) Eric Li and Scratch contributors.</p><p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:</p><p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</p><p>THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</p></details></section>
  </article>;
}
